version: '2'
services:
    sirketimcepte-app:
        image: sirketimcepte
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sirketimcepte-postgresql:5432/sirketimcepte
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=sirketimcepte-elasticsearch:9300
        ports:
            - 8080:8080
    sirketimcepte-postgresql:
        extends:
            file: postgresql.yml
            service: sirketimcepte-postgresql
    sirketimcepte-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sirketimcepte-elasticsearch
